### ISSUE TITLE
The project files were not packaged in when packaging

### ISSUE THREAD

**Issue by abersheeran** [frostming/pdm-packer#2]
This will cause `python app.pyz` to not run correctly when I only give the pyz package.

I checked the source code and this should happen here: https://github.com/frostming/pdm-packer/blob/main/src/pdm_packer/command.py#L100

**Comment by frostming** [comment]
Did you have a name in pyproject.toml? Namely, was the project itself installed into `__pypackages__` as well?

**Comment by abersheeran** [comment]
Yes.

```toml
[project]
dependencies = ["betterproto~=1.2", "httpx~=0.18"]
dynamic = ["classifiers"]
license = {text = "MIT"}
name = "temporary"
requires-python = ">=3.9"
version = "0.1.0"

[project.scripts]
temporary = "temporary:main"

[build-system]
build-backend = "pdm.pep517.api"
requires = ["pdm-pep517"]
```
